name: Typescript Type Check, Prettier and ESLint

on: [push, pull_request]

env:
   DATABASE_URL: "fake"

jobs:
  build:
    name: Typescript Type Check, Prettier and ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Typescript typecheck
        run: npm run typecheck

      - name: Format with Prettier
        run: npm run prettier

      - name: Lint with ESLint
        run: npm run lint